services:
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8889:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  discovery-service:
    build: discovery-service/
    restart: always
    ports:
      - "8761:8761"

  auth-service:
    depends_on:
      - discovery-service
      - db
    build: ./auth-service/
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/auth-service?createDatabaseIfNotExist=true
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/

  product-service:
    depends_on:
      - discovery-service
      - db
    build: ./product-service/
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/product-service?createDatabaseIfNotExist=true
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/

  stock-service:
    depends_on:
      - discovery-service
      - db
    build: ./stock-service/
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/stock-service?createDatabaseIfNotExist=true
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/

  gateway-service:
    depends_on:
      - discovery-service
    build: ./gateway-service/
    restart: always
    ports:
      - "8888:8888"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/

volumes:
  mysql_data:
