apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: default
data:
  # MySQL configuration
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/exam_db
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "false"
  
  # Service URLs for inter-service communication
  AUTH_SERVICE_URL: http://auth-service:8081
  DISCOVERY_SERVICE_URL: http://discovery-service:8761
  GATEWAY_SERVICE_URL: http://gateway-service:8080
  PRODUCT_SERVICE_URL: http://product-service:8082
  STOCK_SERVICE_URL: http://stock-service:8083
  
  # Service ports
  AUTH_PORT: "8081"
  GATEWAY_PORT: "8080"
  PRODUCT_PORT: "8082"
  STOCK_PORT: "8083"
  DISCOVERY_PORT: "8761"
